<?php

/**
* Implements hook_form_FORM_ID_alter().
*/
function reena_user_registration_form_user_register_form_alter(&$form, \Drupal\Core\Form\FormStateInterface $form_state, $form_id) {
  if (\Drupal::currentUser()->isAnonymous()) {
    if($form_id == "user_register_form"){
      $form['field_activity']['#access'] = FALSE;
//      $form['field_activity']['#required'] = FALSE;
      $form['field_profession']['#access'] = FALSE;
//      $form['field_profession']['#required'] = FALSE;
      $form['field_qualification']['#access'] = FALSE;
//      $form['field_qualification']['#required'] = FALSE;
    }
  }
}
